spring:

  application:
    name: HWCreditRequest

  datasource:
    url: jdbc:mysql://localhost:3306/netology
    username: root
    password: pass
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  amqp:
    deserialization:
      trust-all: true
  kafka:
    # Перечисляем всех наших брокеров
    bootstrap-servers: host.docker.internal:29092
    producer:
      # Настраиваем сериализация сообщений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable-metrics-push: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

kafka:
  topics:
    credit-request: credit-request

rabbitmq:
  queues:
    creditapp: creditapp

server:
  port: 5500
